version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/Back/"
    schedule:
      interval: "weekly"
        day: "sunday"
    commit-mesage:
      prefix: "Update NuGet Dependencies for 'Back'"
      include: "scope"
  - package-ecosystem: "nuget"
    directory: "/src/Win"
    schedule:
      interval: "weekly"
        day: "sunday"
    commit-mesage:
      prefix: "Update NuGet Dependencies for 'Back'"
      include: "scope"
