trigger:
- master


pool:
  vmImage: windows-latest


steps:
  - task: VSBuild@1
    inputs:
      solution: '**\*.sln'
      msbuildArgs: '-nologo'
      platform: 'any cpu'
      configuration: 'debug'
      clean: true
      maximumCpuCount: true
      logProjectEvents: false