trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: $(imageName)



steps:

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.0.x'
      includePreviewVersions: true
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--force --nologo'