trigger:
- Azure 
#- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '/p:AllowUnsafeBlocks=true'
    platform: 'Any CPU'
    configuration: 'Release'
    clean: true
    createLogFile: true

#Tests
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'SMW_U.sfc'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        & Back.exe SMW_U.sfc
    workingDirectory: 'src\Back\bin\Release'
    errorActionPreference: 'continue'