version: 2.1

jobs:
  linuxBuild:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Perform Git Checkout"
          command: |
            git checkout dev
            git submodule sync
            git submodule update --init

      - run:
          name: "Build Native Dependencies with CMake"
          command: |
            mkdir ./binCache
            cd ./submodules/asar
            cmake -S ./src -B ./cmakeCache
            cd ./cmakeCache
            make
            cp ./asar/libasar.so ../../../binCache
            cd ../../../

      - run:
          name: "Build .NET Projects"
          command: |
            cd ./src/RetroMole.Launch
            dotnet build
            cp ../../binCache/* ./bin/Debug/net6.0

workflows:
  version: 2
  linux:
    jobs:
      - linuxBuild
