name: BuildAsar
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  BuildAsarLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
              
      # Get CMake
      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2

      # CMake Asar project
      - name: Build and update asar in deps
        shell: bash
        run: |
          mkdir ./bin
          cmake -S ./deps/asar/Asar/src -B ./deps/asar/Asar/out
          cd ./deps/asar/Asar/out/asar
          make
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AsarLinux
          path: ./deps/asar/Asar/out/asar/libasar.so
          retention-days: 10
  
  BuildAsarWindows:
    runs-on: windows-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
        
      # Get CMake
      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2
        
      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      # CMake Asar project
      - name: Build and update asar in deps
        run: |
          mkdir ./bin
          cmake -S ./deps/asar/Asar/src -B ./deps/asar/Asar/out
          cd ./deps/asar/Asar/out/asar
          msbuild asar.vcxproj
          cd ../../../../../
          mv ./deps/asar/Asar/out/asar/Debug/asar.dll ./deps/asar/Asar/out/asar/Debug/libasar.dll

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AsarWindows
          path: ./deps/asar/Asar/out/asar/Debug/libasar.dll
          retention-days: 10
          
  BuildAsarMacOS:
    runs-on: macos-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      # Get CMake
      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2

      # CMake Asar project
      - name: Build and update asar in deps
        shell: bash
        run: |
          mkdir ./bin
          cmake -S ./deps/asar/Asar/src -B ./deps/asar/Asar/out
          cd ./deps/asar/Asar/out/asar
          make
          cd ../../../../../

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AsarMacOS
          path: ./deps/asar/Asar/out/asar/libasar.dylib
          retention-days: 10

  PushUpdatedAsarDeps:
    runs-on: ubuntu-latest
    needs: [BuildAsarLinux, BuildAsarWindows, BuildAsarMacOS]
    steps:
      - name: Pull repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./deps/asar/

      - name: Push updates asar deps
        shell: bash
        run: |
          mv -t ./deps/asar ./deps/asar/Asar[a-zA-Z0-9_-]*/* -v
          rm -d ./deps/asar/Asar[a-zA-Z0-9_-]*
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "[ci-skip][lint-skip] Auto-update deps/asar/libasar.*"
          git push
