name: BuildAsar
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  BuildAsarLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Update submodules
      - name: Update submodules
        run: git submodule update --init   
              
      # Get CMake
      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2

      # CMake Asar project
      - name: Cmake asar
        shell: bash
        run: |
          mkdir ./bin
          cmake -S ./deps/asar/Asar/src -B ./deps/asar/Asar/out
          cd ./deps/asar/Asar/out/asar
          make
          cd ../../../../../
          cp ./deps/asar/Asar/out/asar/libasar.so ./src/deps/asar/libasar.so
          git add .
          git commit -m "[ci-skip][lint-skip][BuildAsar] Update deps/asar/libasar.so"
          git push
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: AsarLinux
          path: ./deps/asar/Asar/out/asar/libasar.so
          retention-days: 30
  
  BuildAsarWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Update submodules
      - name: Update submodules
        run: git submodule update --init 
        
      # Get CMake
      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2
        
      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      # CMake Asar project
      - name: Cmake asar
        run: |
          mkdir ./bin
          cmake -S ./deps/asar/Asar/src -B ./deps/asar/Asar/out
          cd ./deps/asar/Asar/out/asar
          msbuild asar.vcxproj
          cd ../../../../../
          mv ./deps/asar/Asar/out/asar/Debug/asar.dll ./deps/asar/Asar/out/asar/Debug/libasar.dll
          cp ./deps/asar/Asar/out/asar/Debug/libasar.dll ./src/deps/asar/libasar.dll
          git add .
          git commit -m "[ci-skip][lint-skip][BuildAsar] Update deps/asar/libasar.dll"
          git push

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: AsarWindows
          path: ./deps/asar/Asar/out/asar/Debug/libasar.dll
          retention-days: 30
          
  BuildAsarMacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Update submodules
      - name: Update submodules
        run: git submodule update --init 
      
      # Get CMake
      - name: Get CMake
        uses: lukka/get-cmake@v3.21.2

      # CMake Asar project
      - name: Cmake asar
        shell: bash
        run: |
          mkdir ./bin
          cmake -S ./deps/asar/Asar/src -B ./deps/asar/Asar/out
          cd ./deps/asar/Asar/out/asar
          make
          cd ../../../../../
          cp ./deps/asar/Asar/out/asar/libasar.dylib ./src/deps/asar/libasar.dylib
          git add .
          git commit -m "[ci-skip][lint-skip][BuildAsar] Update deps/asar/libasar.dylib"
          git push

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: AsarMacOS
          path: ./deps/asar/Asar/out/asar/libasar.dylib
          retention-days: 30
