name: Lint Code Base
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      validateall:
        description: 'Lint all files if true, just lint latest changes if false'
        required: true
        default: 'true'

jobs:
  Lint:
    if: ${{ !contains(github.event.head_commit.message, '[lint-skip]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE:
            ${{
              !(env.GITHUB_EVENT_NAME == 'workflow_dispatch'"') ||
              github.event.inputs.validateall == 'true'
            }} # black magic boolean stuff to default to default to true when run automatically, but check input when run manually
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: src/.*
          FILTER_REGEX_EXCLUDE: src/Asar/.*|src/ImGui.NET/.*
