name: Test
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  LinuxTest:
    if: 
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        !(
          contains(github.event.head_commit.message, '[windows-only]') ||
          contains(github.event.head_commit.message, '[macos-only]') ||
          contains(github.event.head_commit.message, '[linux-skip]') ||
          contains(github.event.head_commit.message, '[ci-skip]')
        )
        }}
    runs-on: ubuntu-latest
    steps: 
      # Download repo
      - name: Pull repo
        uses: actions/checkout@v3.0.1
        with:
          submodules: 'recursive'

      # Setup dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'
      
      # Run unit tests
      - name: Run unit tests
        run: dotnet test ./src/Mole.sln -o ./bin

  WindowsTest:
    if: 
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        !(
          contains(github.event.head_commit.message, '[linux-only]') ||
          contains(github.event.head_commit.message, '[macos-only]') ||
          contains(github.event.head_commit.message, '[windows-skip]') ||
          contains(github.event.head_commit.message, '[ci-skip]')
        )
        }}
    runs-on: windows-latest
    steps: 
      # Download repo
      - name: Pull repo
        uses: actions/checkout@v3.0.1
        with:
          submodules: 'recursive'

      # Setup dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      # Run unit tests
      - name: Run unit tests
        run: dotnet test ./src/Mole.sln -o ./bin


  MacOSTest:
    if: 
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        !(
          contains(github.event.head_commit.message, '[windows-only]') ||
          contains(github.event.head_commit.message, '[linux-only]') ||
          contains(github.event.head_commit.message, '[macos-skip]') ||
          contains(github.event.head_commit.message, '[ci-skip]')
        )
        }}
    runs-on: macos-latest
    steps: 
      # Download repo
      - name: Pull repo
        uses: actions/checkout@v3.0.1
        with:
          submodules: 'recursive'

      # Setup dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      # Run unit tests
      - name: Run unit tests
        run: dotnet test ./src/Mole.sln -o ./bin
