name: Test
on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  LinuxTest:
    if: 
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        !(
          contains(github.event.head_commit.message, '[windows-only]') ||
          contains(github.event.head_commit.message, '[macos-only]') ||
          contains(github.event.head_commit.message, '[linux-skip]') ||
          contains(github.event.head_commit.message, '[ci-skip]')
        )
        }}
    runs-on: ubuntu-latest
    steps: 
      # Download repo
      - uses: actions/checkout@v2

      # Update submodules
      - name: Update submodules
        run: git submodule update --init

      # Setup dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.401'
      
      # Download asar artifact to output
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          workflow: 'asar.yaml'
          name: 'AsarLinux'
          path: './bin'

      # Copy cimgui to output
      - name: Copy cimgui
        shell: bash
        run: cp "./src/ImGui.NET/deps/cimgui/linux-x64/cimgui.so" "./bin/cimgui.so"

      # Run unit tests
      - name: Run unit tests
        run: dotnet test ./src/MOLE.sln -o ./bin


  WindowsTest:
    if: 
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        !(
          contains(github.event.head_commit.message, '[linux-only]') ||
          contains(github.event.head_commit.message, '[macos-only]') ||
          contains(github.event.head_commit.message, '[windows-skip]') ||
          contains(github.event.head_commit.message, '[ci-skip]')
        )
        }}
    runs-on: windows-latest
    steps: 
      # Download repo
      - uses: actions/checkout@v2

      # Update submodules
      - name: Update submodules
        run: git submodule update --init

      # Setup dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.401'
      
      # Download asar artifact to output
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          workflow: 'asar.yaml'
          name: 'AsarWindows'
          path: './bin'

      # Copy cimgui to output
      - name: Copy cimgui
        shell: bash
        run: cp "./src/ImGui.NET/deps/cimgui/win-x64/cimgui.dll" "./bin/cimgui.dll"

      # Run unit tests
      - name: Run unit tests
        run: dotnet test ./src/MOLE.sln -o ./bin


  MacOSTest:
    if: 
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        !(
          contains(github.event.head_commit.message, '[windows-only]') ||
          contains(github.event.head_commit.message, '[linux-only]') ||
          contains(github.event.head_commit.message, '[macos-skip]') ||
          contains(github.event.head_commit.message, '[ci-skip]')
        )
        }}
    runs-on: macos-latest
    steps: 
      # Download repo
      - uses: actions/checkout@v2

      # Update submodules
      - name: Update submodules
        run: git submodule update --init

      # Setup dotnet
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.401'
          
      # Download asar artifact to output
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.15.0
        with:
          workflow: 'asar.yaml'
          name: 'AsarMacOS'
          path: './bin'

      # Copy cimgui to output
      - name: Copy cimgui
        shell: bash
        run: cp "./src/ImGui.NET/deps/cimgui/osx-x64/cimgui.dylib" "./bin/cimgui.dylib"

      # Run unit tests
      - name: Run unit tests
        run: dotnet test ./src/MOLE.sln -o ./bin
